version: "3.7"
services:
  app:
    build:
      target: localdev
      args:
        PUID: 1000
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/cocktails
      - ./resources/php.dev.ini:/usr/local/etc/php/conf.d/local.ini

  horizon:
    build:
      target: localdev
      args:
        PUID: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: php artisan horizon
    volumes:
      - ./:/var/www/cocktails

  # minio:
  #   image: 'bitnami/minio:latest'
  #   ports:
  #     - '7000:9000'
  #     - '7001:9001'
  #   environment:
  #     - MINIO_ROOT_USER=minio-root-user
  #     - MINIO_ROOT_PASSWORD=minio-root-password
  #   volumes:
  #     - miniiodata:/data

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/cocktails
      - ./resources/nginx.dev.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.5
    environment:
      - MEILI_MASTER_KEY=masterKeyThatIsReallyReallyLong4Real
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilidata:/meili_data

volumes:
  meilidata:
  miniiodata:
