services:
  app:
    build:
      target: dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: .
      dockerfile: unprivileged.Dockerfile
    container_name: app
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: "bass-php"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/cocktails
      - ./resources/docker/localdev/php.ini:/usr/local/etc/php/php.ini

  task:
    build:
      target: dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: .
      dockerfile: unprivileged.Dockerfile
    command: ["php", "/var/www/cocktails/artisan", "schedule:work"]
    environment:
      PHP_FPM_POOL_NAME: "bass-task"
    volumes:
      - ./:/var/www/cocktails

  horizon:
    build:
      target: dev
      args:
        USER_ID: 1000
        GROUP_ID: 1000
      context: .
      dockerfile: unprivileged.Dockerfile
    restart: unless-stopped
    environment:
      PHP_FPM_POOL_NAME: "bass-horizon"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["php", "/var/www/cocktails/artisan", "horizon"]
    volumes:
      - ./:/var/www/cocktails

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/cocktails
      - ./resources/docker/localdev/nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.7
    environment:
      - MEILI_MASTER_KEY=masterKeyThatIsReallyReallyLong4Real
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilidata:/meili_data

volumes:
  meilidata:
  miniiodata:
