services:
  app:
    build:
      target: localdev
      args:
        PUID: 1000
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/cocktails
      - ./resources/docker/localdev/php.ini:/usr/local/etc/php/php.ini

  horizon:
    build:
      target: localdev
      args:
        PUID: 1000
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: php artisan horizon
    volumes:
      - ./:/var/www/cocktails

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/cocktails
      - ./resources/docker/localdev/nginx.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.6
    environment:
      - MEILI_MASTER_KEY=masterKeyThatIsReallyReallyLong4Real
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilidata:/meili_data

volumes:
  meilidata:
  miniiodata:
