version: "3.7"
services:
  app:
    build:
      args:
        user: developer
        uid: 1000
      context: .
      dockerfile: Dockerfile.dev
    container_name: app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/cocktails
      - ./resources/php.dev.ini:/usr/local/etc/php/conf.d/local.ini

  # queue:
  #   build:
  #     args:
  #       user: developer
  #       uid: 1000
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   restart: always
  #   command: php artisan queue:work
  #   volumes:
  #     - ./:/var/www/cocktails

  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/cocktails
      - ./resources/nginx.dev.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    restart: unless-stopped

  meilisearch:
    image: getmeili/meilisearch:v1.3.2
    environment:
      - MEILI_MASTER_KEY=masterKeyThatIsReallyReallyLong4Real
    restart: unless-stopped
    ports:
      - 7700:7700
    volumes:
      - meilidata:/meili_data

volumes:
  meilidata:
