name: Test application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'

    - uses: actions/checkout@v3

    - name: Copy .env
      run: cp .env.dist .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit tests/

    - name: Execute PHPStan
      run: composer static
