name: Run PHP checks

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - uses: actions/checkout@v3

    - name: Meilisearch (latest version) setup with Docker
      run: docker run -d -p 7700:7700 getmeili/meilisearch:latest meilisearch --master-key=masterKey --no-analytics

    - name: Copy .env
      run: cp .env.dist .env

    - name: Install Dependencies
      run: composer install --prefer-dist --no-progress

    - name: Generate key
      run: php artisan key:generate

    - name: Check coding style
      run: vendor/bin/ecs --clear-cache

    - name: Execute tests (Unit and Feature tests) via PHPUnit
      run: vendor/bin/phpunit tests/

    - name: Execute PHPStan
      run: composer static
